/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui {
    export class LoadingUI extends View {
		public lab_Progress:Laya.Label;
		public img_Progress:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Loading");
        }
    }
    export class SelectUI extends View {
		public round_Lamp:Laya.Sprite;
		public btn_Exit:Laya.Image;
		public btn_First_:Laya.Image;
		public btn_First:Laya.Label;
		public btn_Second_:Laya.Image;
		public btn_Second:Laya.Label;
		public btn_Third_:Laya.Image;
		public btn_Third:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Select");
        }
    }
    export class StartGameUI extends View {
		public btn_StartGame:Laya.Image;
		public btn_Imgs:Laya.Image;
		public btn_About:Laya.Image;
		public lab_StartGame:Laya.Label;
		public round_Lamp:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("StartGame");
        }
    }
}
export module ui.SelectBox {
    export class SelectBoxUI extends View {
		public round_Lamp:Laya.Sprite;
		public moster:Laya.Image;
		public panel_ShowBox:Laya.Panel;
		public btn_Exit:Laya.Image;
		public sprite_SelectBox:Laya.Sprite;
		public img_SelectBox:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("SelectBox/SelectBox");
        }
    }
}